### PR TITLE
Add first and last page buttons to pagination, issue (#17)

### PR DESCRIPTION
**Pull request by Nadzt**
Added first and last page buttons maintaining the ellipsis when necessary, also deleted some duplicated code on the render map of the buttons

### CODE REVIEW

**Comment by ysknsid25** [comment]
@Nadzt 

Please make a few corrections before we start the review.

# 1. please make sure your branch is merged to dev and not master

image

# 2. the test code is throwing an error

Please add the test code to match the fixes. Note that the current specification is to display page numbers in [these four patterns](https://github.com/ysknsid25/booby/pull/15), so please do not change this specification.
(The same applies to the number of buttons displayed by default.)

For example,

1 2 3 4 5 ... 99

This is the correct way to display the page numbers.

and execute `npm run test:all`

**Comment by Nadzt** [comment]
Hi @ysknsid25 

Sorry, i didnt know about the patterns and took some liberties (lol), however i already fixed them to match the link you provided,
here's a preview:
Pattern 1:
pattern1

Pattern 2 and 3:
pattern2-3

Pattern 4:
pattern4

i also made some changes in the test file to match these changes, however i've run into an obstacle i'd like to discuss with you
it's about page 4 (and 4th page from last too):

how would you like it to be handled:
option 1:
option1

option 2:
option2

option 3:
option3

**Comment by ysknsid25** [comment]
@Nadzt 

Option2 is preferred👍

**Comment by Nadzt** [comment]
up for review

**Review by ysknsid25 — CHANGES_REQUESTED** [review]
Please add 3 new test patterns.

1. if the last page number is shown in pattern 2
2. if the first page number is displayed in case of pattern 3
3. whether the first and last page numbers are shown in case of pattern 4

You may write the test content in English 🙏

**Comment by Nadzt** [comment]
@ysknsid25
Done, let me know if you need anything else

**Review by ysknsid25 — APPROVED** [review]
LGTM, Thanks👍

By the way, where did you hear about this project? And why did you decide to contribute?

**Comment by Nadzt** [comment]
I found it through https://goodfirstissues.com/ (which i got from https://www.firsttimersonly.com/)
The issue 17 poped up as one of the latest, and i wanted to help with something.

**Comment by ysknsid25** [comment]
Wow! This is a great web service. I bookmarked it myself 🙏.
Thanks for your contrib 😊.

**Comment by Nadzt** [comment]
Thank you for your patience too, i still gotta figure out all the nuances of contributions lol

**Pull request merged**
